In [4]:
from stock_class import Stock, StockList
from portfolio_class import Portfolio, PortfolioList
from broker import IBroker
import pandas as pd 
import numpy as np
import time
import cProfile, pstats, io
import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from concurrent.futures import ProcessPoolExecutor

# constants
from config import ticker_list, bronze, silver, gold, forecast_folder, model_folder, model_meta_file, portfolio_folder

In [2]:
stock_list = StockList(tickers)
stock_list.load_data(path=gold)

portfolio = Portfolio(stock_list=stock_list, features=tickers)

broker = IBroker()
broker.connect()

Sector not found. Assigning `Unknown`
Sector not found. Assigning `Unknown`
Sector not found. Assigning `Unknown`

RuntimeError: This event loop is already running

Peer closed connection.

In [3]:
for ticker in tickers:
    broker.get_stock_price(ticker)
    time.sleep(3)

RuntimeError: This event loop is already running

In [3]:
p.load_weights('/Users/gergelyfazekas/Documents/python_projects/trading_new_structure/data/portfolios/gen3_id0_2025-07-14 14:38:25.321841.json')

In [4]:
# We should go from pulling the IBKR data to having a forecast for the next day
forecasts = [1,2,3]
df = pd.DataFrame(dict(zip(tickers, forecasts)), index=[datetime.datetime.now()])

In [ ]:
p.decide(dt=df.index[0], data=df.to_numpy())

In [ ]:
p.decision_to_action(decision=p.decide(dt=df.index[0], data=df.to_numpy()))

In [15]:
df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6]})
pd.DataFrame(dict(df.iloc[-1, :]), index=[df.iloc[-1, :].name])

   a  b
2  3  6

In [17]:
df.iloc[0, 0] = np.nan

In [27]:
df[df.isna().any(axis=1)]

    a  b
0 NaN  4